name: Docker images building and pushing
on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}



      -
        name: Docker meta for Postman executor
        id: meta_postman_executor
        uses: docker/metadata-action@v3
        with:
          images: kubeshop/kubtest-postman-executor
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - 
        name: Build Postman Executor
        uses: docker/bake-action@v1
        with:
          files: |
            build/executor/docker-bake.hcl
            ${{ steps.meta_postman_executor.outputs.bake-file }}
          targets: build
          set: build.args.TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          push: true

      - name: Trigger Helm Charts build
        run: |
          curl -X POST https://api.github.com/repos/kubeshop/helm-charts/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "build"}'
          

